export PATH="${HOME}/bin:/opt/bin/:/usr/local/bin:${PATH}"
export PROFILE=HOME

export JAVA_HOME="/usr/java/latest"

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
GPG_TTY=$(tty)
export GPG_TTY
#if [ -f "${HOME}/.gpg-agent-info" ]; then
#   . "${HOME}/.gpg-agent-info" > /dev/null 2>&1
#  export GPG_AGENT_INFO
#  export SSH_AUTH_SOCK
#  export SSH_AGENT_PID
#fi
